name: Build & Upload Python Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      subdir:
        type: choice
        description: "Which sub-package(s) to build?"
        required: true
        default: "all"
        options:
          - all
          - jobmon_client
          - jobmon_core
          - jobmon_server

permissions:
  contents: read

jobs:
  build_and_publish:
    environment: 'deploy'
    runs-on: ubuntu-latest

    # A matrix with three sub-packages. We'll run the same job for each.
    strategy:
      matrix:
        subdir: [ "jobmon_client", "jobmon_core", "jobmon_server" ]
      # Controls how many can run in parallel. 1 = sequential.
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4
        with:
          # Important for setuptools-scm to detect tags
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      # This step runs first in every matrix job, but if the user
      # only wants one subdir, we skip.
      - name: Skip if the chosen subdir doesn't match
        if: ${{ inputs.subdir != 'all' && matrix.subdir != inputs.subdir }}
        run: |
          echo "Skipping ${{ matrix.subdir }} because user chose ${{ inputs.subdir }}"

      # Actually build the package only if we're chosen or user picked 'all'.
      - name: Build package
        if: ${{ inputs.subdir == 'all' || matrix.subdir == inputs.subdir }}
        run: |
          echo "Building package in ${{ matrix.subdir }}..."
          cd ${{ matrix.subdir }}
          python -m build --outdir dist

      - name: Publish to PyPI
        if: ${{ inputs.subdir == 'all' || matrix.subdir == inputs.subdir }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          dists: "${{ matrix.subdir }}/dist/*"
