name: Build & Upload Python Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      subdir:
        type: choice
        description: "Which sub-package(s) to build?"
        required: true
        default: "all"
        options:
          - all
          - jobmon_client
          - jobmon_core
          - jobmon_server

permissions:
  contents: read

jobs:
  build_and_publish:
    environment: 'deploy'
    runs-on: ubuntu-latest
    # If build-time dependencies for your packages are in Artifactory,
    # you might need this:
    # env:
      # UV_EXTRA_INDEX_URL: ${{ secrets.IHME_ARTIFACTORY_PYPI_SIMPLE_URL }}
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        subdir: [ "jobmon_client", "jobmon_core", "jobmon_server" ]
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install uv and build tool
        run: |
          python -m pip install --upgrade pip uv # Install/upgrade pip first, then uv
          uv pip install --system build # Install build using uv

      # Optional: Configure uv cache (can be useful if build has many uv-managed deps)
      # - name: Configure uv cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/uv
      #     key: ${{ runner.os }}-uv-publish-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-uv-publish-

      - name: Skip if the chosen subdir doesn't match
        if: ${{ inputs.subdir != 'all' && matrix.subdir != inputs.subdir }}
        run: |
          echo "Skipping ${{ matrix.subdir }} because user chose ${{ inputs.subdir }}"

      - name: Build package
        if: ${{ inputs.subdir == 'all' || matrix.subdir == inputs.subdir }}
        run: |
          echo "Building package in ${{ matrix.subdir }}..."
          cd ${{ matrix.subdir }}
          python -m build --outdir dist

      - name: Publish to PyPI
        if: ${{ inputs.subdir == 'all' || matrix.subdir == inputs.subdir }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages-dir: "${{ matrix.subdir }}/dist"